//* Main Java File
package HorrorWalkingSimulator;

// Imports
import java.util.Scanner;


import ANSI.ConsoleColors;

public class HorrorWalkingSimulator
{
    //? Scanner errors out when contained within methods. Apparently it's something to do with "You're trying to read input from a Scanner when there's no more input available." But it works when placed out here
    static Scanner in = new Scanner(System.in);

    public static void main(String[] args)
    {
        Introduction();

        int wantsToExit = Senario1();
        Exit(wantsToExit);

        wantsToExit = Senario2();
        Exit(wantsToExit);

        wantsToExit = Senario3();
        Exit(wantsToExit);
    }

    public static void Exit(int answer)
    {
        // For choice 3 in the senario questions, they all represent exiting the application.
        if (answer == 3)
        {
            System.exit(0);
        }
    }

    public static void Introduction()
    {
        // Title
        System.out.println(ConsoleColors.WHITE_BOLD + "\n\n\t| The Wendigo's Whisper: A Choose-Your-Own-Adventure Story (Generated by ChatGPT) |" + ConsoleColors.RESET);
        System.out.println("\t| OpenAI. (2024). ChatGPT [Large language model]. https://chatgpt.com |\n\n");

        // Introduction
        System.out.println("Sam had always enjoyed hiking alone. The solitude of the forest was comforting, a place where she could escape the stress of everyday life. That weekend, she decided to visit Blackwood Forest, a place that had always intrigued her but also stirred a strange unease. Locals often spoke of strange disappearances, but Sam brushed off the rumors as nothing more than old wives’ tales.\n\nWith a full backpack and an optimistic mindset, Sam entered the forest just before dusk, determined to spend a quiet night under the stars. But as the sun began to sink behind the trees, a chilling wind picked up, and a deep sense of dread settled in her gut. Something was wrong.\n\nThe further she walked, the quieter the forest became. No birds, no animals—just the eerie sound of the wind through the trees and... something else. A distant whisper, calling her name.");
    }

    public static int Senario1()
    {
        // More story
        System.out.println("As Sam walks deeper into the forest, she hears the whisper again, this time closer. It's soft, barely audible, but unmistakable. She feels an urge to investigate but also a strong instinct to leave the forest immediately.\n");

        // Ask user for input
        System.out.println("Senario 1: Do you\n");
        System.out.println("1. Investigate the source of the whisper?\n");
        System.out.println("2. Turn around and head back toward the car?\n");
        System.out.println("3. Exit the application\n");

        int answer = in.nextInt();

        switch (answer)
        {
            // option 1 is death, 2 continues the story
            case 1:
                System.out.println("Sam’s curiosity gets the better of her, and she follows the whisper, veering off the main trail and into the thick underbrush. As she presses forward, the whisper grows louder, more distinct. Her heart pounds in her chest, and the air around her seems to thicken.\n\nSuddenly, she stumbles into a small clearing. In the center stands a tall figure, its back turned toward her. It’s unnaturally thin, with elongated limbs and matted fur clinging to its body. Sam freezes in place as the figure slowly turns its head, revealing hollow eyes and a gaping, tooth-filled maw.\n\nShe tries to scream, but no sound comes out. The Wendigo lunges, and everything goes dark.\n\nBAD END: You should have trusted your instincts. The Wendigo does not show mercy.");
                System.exit(0);
                break;
            case 2:
                System.out.println("Sam turns on her heel and heads back the way she came, her heart racing. The whisper fades as she picks up the pace, her footsteps quickening. Relief washes over her when she sees the familiar shape of her car through the trees, but just as she reaches for the door, the wind howls, carrying the sound of a distant scream.");
                break;
            case 3:
                System.out.println("Exiting application...");
                break;
            default:
                System.err.println("Invalid choice");
        }

        return answer;
    }

    public static int Senario2()
    {
        // More story
        System.out.println("She hesitates, torn between the safety of her car and the possibility that someone is in trouble.\n");

        // Ask user for input
        System.out.println("Senario 2: Do you\n");
        System.out.println("1. Ignore the scream and drive away?\n");
        System.out.println("2. Grab a flashlight and go back to investigate the scream?\n");
        System.out.println("3. Exit the application\n");

        int answer = in.nextInt();

        switch (answer)
        {
            // option 1 premptively ends the story, skipping senario 3. option 2 continues the story.
            case 1:
                System.out.println("Sam jumps into the car, her hands shaking as she fumbles for the keys. The scream echoes again, louder this time, but she forces herself to ignore it. The car’s engine roars to life, and she speeds down the dirt road, desperate to put as much distance between herself and the forest as possible.\n\nAs she drives, she glances in the rearview mirror. Her heart skips a beat. Standing at the edge of the road is a tall, gaunt figure, watching her as she disappears into the night.\n\nSam escapes, but she’ll never forget the sound of that whisper—or the creature that still lurks in the shadows of Blackwood Forest.\n\nGOOD END: You survived, but something still watches.");
                System.exit(0);
                break;
            case 2:
                System.out.println("Sam grabs her flashlight and reluctantly heads back into the forest. The scream echoes again, but it sounds different this time—more distorted, unnatural. She pushes through the underbrush, her heart hammering in her chest.\n\n");
                break;
            case 3:
                System.out.println("Exiting application...");
                break;
            default:
                System.err.println("Invalid choice");
        }

        return answer;
    }

    public static int Senario3()
    {
        // More story
        System.out.println("Suddenly, she spots a small cabin in the distance, barely visible through the trees. The scream came from that direction. As she approaches, the cabin door swings open on its own, creaking on rusty hinges.\n");

        // Ask user for input
        System.out.println("Senario 3: Do you\n");
        System.out.println("1. Enter the cabin?\n");
        System.out.println("2. Back away and leave?\n");
        System.out.println("3. Exit the application\n");

        int answer = in.nextInt();

        switch (answer)
        {
            // option 1 is death, option 2 is the best ending
            case 1:
                System.out.println("Sam steps into the cabin, her flashlight beam cutting through the darkness. The inside is decrepit, with old furniture scattered across the floor and strange symbols etched into the walls. As she steps further inside, she hears a low growl from the shadows.\n\nBefore she can react, the Wendigo emerges from the darkness, its eyes gleaming with hunger. It’s too late to run.\n\nBAD END: The Wendigo has found you.");
                System.exit(0);
                break;
            case 2:
                System.out.println("Sam stares at the cabin for a moment longer before deciding to leave. Something about the place feels deeply wrong, and every instinct in her body screams at her to get out. She turns and runs back toward the main trail, not stopping until she’s far from the cabin.\n\nThe whisper is gone, and the forest has returned to its eerie silence. As she makes her way back to her car, Sam can’t shake the feeling that she was being lured into a trap.\n\nShe drives away, vowing never to return to Blackwood Forest.\n\nGOOD END: You listened to your instincts and survived.\n\n");

                System.out.println("Sam's adventure in Blackwood Forest was harrowing, and though she made it out alive, the encounter left her shaken. The Wendigo is patient, always lurking, waiting for its next victim to wander too far from safety. Would you be able to survive the Wendigo’s whispers, or would curiosity lead you into the creature’s clutches?\n\nThe End");
                break;
            case 3:
                System.out.println("Exiting application...");
                break;
            default:
                System.err.println("Invalid choice");
        }
        return answer;
    }
}

